### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by curator888** [blacklanternsecurity/writehat#1]
Would it be possible to turn this into a docker image so it can be added to this project https://github.com/SelfhostedPro/selfhosted_templates/tree/portainer-2.0.

**Comment by TheTechromancer** [comment]
That's very possible; feel free to play around with it.  WriteHat is made up of five separate containers which are already deployable via a Docker oneliner (see the readme).  We don't necessarily recommend compiling them all into a static blob, since if one container gets an update (e.g. the Chromium/Selenium instance), the blob would need to be recreated again.
