### ISSUE TITLE
Separate template for the front page?

### ISSUE THREAD

**Issue by keesj-exset** [blacklanternsecurity/writehat#12]
Hello,

In the last couple of days I have been making small modifications to Writehat. I have mainly been adding a new finding type. This was not trivial as I hoped, mainly because I had to make many small modifications to finding group, engagement findings, findings, the database export and import. This part of the modifications are starting to work but the end result will remain hard to maintain. I am novice at django so that might explain why it took a few days but to me it looks like it would be nice to refactor the code to only have one type of finding group (with a finding type field?). This would remove some of the duplication but I don't know the drawback (perhaps in the database export?). Anyway... I made the modification and I am quite happy about write hat as tool. I also managed to create a script to import code annotations(We often do code review and use a tool to make the annotations) all in all .. quite nice.

I am now trying to modify the title page. I would like to add a background image to it . I am not quite sure how to tackle this. It looks like I would like to be able to select a different page template for this component but I don't understand well enough yet how the report is created. From code inspection it looks like the render method is called on all components (and a htmlTemplate) appear but I don't understand if it **would** be possible to select a different page template for the titlePage (or even generic Component)

The second way I can imagine is to add an image to the title page component or create my own. Any guidance on how I should modify the code to allow to add a background image to the titlepage without adding this same background to all pages?

**Comment by TheTechromancer** [comment]
Hello!

First off, I can confirm that adding a new finding type is indeed non-trivial and not easy to maintain.  This isn't by design, but it did turn out that way.

Modifying the title page should be pretty straightforward.  You can move/resize the company logo via HTML and CSS, and the image from the page template will be used.  The "Background Image" is applied to all pages, but the "Company Logo" is only used on the title page.

If you prefer to hardcode a custom image, it might be best to use the inline method like so:
```
<div>
  <p>Taken from wikpedia</p>
  <img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
    AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
        9TXL0Y4OHwAAAABJRU5ErkJggg=="/>
</div>
```

Also, you can always create your own custom component (perhaps using the title page as a starting point).  There are instructions for this in the README.

Good luck!

**Comment by kerrymilan** [comment]
Findings and finding groups could probably use some refactoring; that part of the code base has grown quite a bit since its inception. It's likely that a lot of the duplicated logic could be consolidated into the base class, but you still wind up with some fun double inheritance issues dealing with finding types and scoring types ([Report, Database] x [CVSS, DREAD, Proactive]). We explored using a single class with a type field but decided it wasn't practical since there was minimal overlap between each type's forms, templates, and scoring logic. If you want to explore that avenue some more, we welcome your feedback and I'm happy to answer any questions you have along the way.

To your second point about the title page, adding a custom component to introduce a new background image should be straightforward, but removing the template's existing background image is more challenging: it's applied at the page level, and individual components don't really have any knowledge of or control over the pages that contain them. If you're certain that the title page will always be the first page of the document, you can get around it by adding something like this to your title page component's stylesheet:

```
@media print {
  @page:first {
    background-image: url(<your-image>) !important;
  }
}
```

If you want to control that from the interface on a per-template basis without modifying the stylesheets, you should be able to add a new background image ID field to `lib/pageTemplate.py` to store a separate image for the first page. Then, modify the `<style>` block at the end of `templates/reportTemplates/reportDependencies.html` to apply the new field to `.pagedjs_page:first`. 

A more nuanced solution than that will likely require adding logic to propagate component CSS classes up to the page(s) that contain them.

Again, keep us posted and let us know if you have any questions. Thanks so much for the feedback!

**Comment by keesj-exset** [comment]
Thanks for the ideas and feeback! I will keep you posted.

**Comment by Wherekonshade** [comment]
Hi everybody :)
I contacted @keesj-exset about this issue and he told me, that he ran out of steam, but I managed to implement this according to my needs. I feel like this issue is too specific to make a pull request out of it, since most people will prefer how it is implemented right now. But if anybody needs help with this, feel free to contact me: Wherekonshade@web.de 
:)
This issue can probably be closed.
