### ISSUE TITLE
Add support for SAML/OpenID Connect

### ISSUE THREAD

**Issue by craftbyte** [blacklanternsecurity/writehat#2]
A lot of companies are moving to SAML or OpenID Connect based authentication for their apps. It allows for use of 2FA, client compliance, security by end-user apps not even passing passwords, etc.

Do you think it would be possible to support at least OpenID Connect through an OAuth library?

**Comment by TheTechromancer** [comment]
It would be possible; the project is written in Django which already supports many authentication backends (including OAuth) through third-party libraries.  This isn't something we're currently working on, but pull requests are always welcome.  Otherwise, it may become part of the roadmap later on if there's enough demand for it.
