### ISSUE TITLE
Findings??

### ISSUE THREAD

**Issue by emilyanncr** [blacklanternsecurity/writehat#38]
I just build this on my box and am navigating around.  Are there no findings already in the database??  The wiki doesn't address findings at all (outside explaining finding groups)  Do I need to import them from somewhere??  Surely we're not expected to enter every single finding on our own, right?

**Comment by aconite33** [comment]
Hey @emilyanncr 
WriteHat is built modular so that you can create your own findings and template them! So when you start writing reports, you can pull in from other sources, templates, or standards (For example CWE's would be a good place to start! - https://cwe.mitre.org/).

From there, you can build faster reports by using the templated findings and just fill in specifics, for example CVSS Environmental Scoring.

Currently we don't have a default list of findings database prebuilt, but we do accept pull requests!

**Comment by emilyanncr** [comment]
Hmm ok, it says one of the features of WriteHat is a 'findings database', so it makes it sound as though sample findings have been included.
Serpico has a bunch of template-findings in .json format. It'd be great if Writehat provided a way to import them.
https://github.com/ministryofjustice/serpico-templates/tree/master/template_findings
