### ISSUE TITLE
Build Issues with Custom Password Configurations

### ISSUE THREAD

**Issue by hummelm10** [blacklanternsecurity/writehat#4]
I've been trying to customize the passwords set in the writehat.conf and docker-compose.yml and run into two behaviors that I can't seem to track down. 

1. Updating the SQL or MongoDB password
Updating the SQL and/or MongoDB password in writehat.conf and docker-compose.yml causes the build to error out and the writehat container just endlessly restarts with an access denied 
![image](https://user-images.githubusercontent.com/10765528/100916648-03533e00-34a4-11eb-9ba6-d734925b6733.png)

After adding a print to the manage.py script I can see it's failing on the first run of the manage.py (`manage.py makemigrations writehat`).

2. Assuming I don't change the SQL or MongoDB password and the build finishes the `admin_password` change in writehat.conf is never reflected in the application. Whatever I put there in the writehat.conf file the password remains the default from the oneliner setup. If I change the `admin_username` to something like 'superuser' and the `admin_password` a new admin is created with the custom username/password but the default admin is also still created with the default password. 
![image](https://user-images.githubusercontent.com/10765528/100919933-778fe080-34a8-11eb-97a1-6974c6b51d81.png)

The only way it seems to change the default admin password is within the application itself after initial setup. If this is working as intended then it should be reflected in the setup/install notes.

**Comment by TheTechromancer** [comment]
The `admin` account is created the first time the containers are launched (it is inserted into the MySQL DB).  If you need to change its password after that, you need to either log in with the original password or reset it using `manage.py`.  As for the MongoDB and MySQL passwords, I believe they apply on "first run" as well.  That's why it's important that you change all the passwords _before_ starting the containers for the first time.

The easiest solution for you might be to run `docker-compose down` which will delete the containers, `sudo rm -rf` the `mongo` and `mysql` directories, then start over with the passwords you want to use.

**Comment by hummelm10** [comment]
I just deleted the entire writehat directory and recloned the repo after doing `docker-compose down` and it worked just fine. Must have happened when I did the oneliner setup to try the platform out and then tried to rebuild it again with the changes. Thanks! I'd recommend making a note of that somewhere in the install so someone doesn't go down the same path I did.
