### ISSUE TITLE
Manual file level backup not working

### ISSUE THREAD

**Issue by thejohnbrown** [blacklanternsecurity/writehat#5]
Restoring from a backup created from tarring up the `mongo mysql` and  `writehat/migrations` folders doesn't seem to work, unless i'm doing something wrong. I created a backup of the folders, made changes to my current application i.e. deleted a report and then tested restoring from this backup by just extracting over the top of my current install. When I went back into the application I could see that the previously deleted report was now restored, however when clicking on the report it would return a 500 error in the browser. 

Steps to reproduce (basically as you have described in the README):

1. Stop the service `systemctl stop writehat`
2. Backup the files `sudo tar --same-owner -cvzpf db_backup.tar.gz mongo mysql writehat/migrations`
3. Backup writehat/migrations `mv writehat/migrations writehat/migrations.bak`
4. Delete a report in the application
5. Restore from the backup `sudo tar --same-owner -xvpzf db_backup.tar.gz`
6. Start the service again `systemctl start writehat`

You'll see that the report has been restored but clicking on it returns a 500 status code.

**Comment by kerrymilan** [comment]
I think the problem is that the backups are restored on top of the existing data. Before item 5 in your list, try removing `mongo` and `mysql`:
```
...
mkdir db.old
sudo mv mongo mysql db.old
sudo tar --same-owner -xvpzf db_backup.tar.gz
...
```

The issue seems to be that Mongo is generating new journal files that don't get removed during the restore, so it crashes on startup when the storage engine encounters a checksum error. 

If that addition fixes the issue, and I'll update the restore instructions.

**Comment by thejohnbrown** [comment]
Apologies it took me so long to get back to you, Christmas holidays and all.

I just tested your fix above and it works great, thank you.
