### ISSUE TITLE
connection issue to mysql

### ISSUE THREAD

**Issue by GreenKnightDigital** [blacklanternsecurity/writehat#54]
I keep getting django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")

I have changed 'mysql' to '127.0.0.1' in the writehat.conf file to try and fix the issue but I get this error either way.

The connection failure happens in the socket.py file

**Comment by thejohnbrown** [comment]
Check `docker ps -a`, is the writehat MySQL container running? If yes, are the credentials correct? Can you login to it manually using MySQL command line tool?

**Comment by GreenKnightDigital** [comment]
Just noticed these warnings while running `docker-compose down` 

WARNING: The t2897 variable is not set. Defaulting to a blank string.
WARNING: The t6216 variable is not set. Defaulting to a blank string

**Comment by TheTechromancer** [comment]
I'm having difficulty reproducing this, however it is pretty normal to see mysql-related errors when bringing up docker-compose, since the mysql container takes a long time to start.

Can you make sure you're operating from a fresh clone of writehat, and then run `docker-compose down` before you run `docker-compose up`? You can paste the output of `docker-compose up` here.

**Comment by unixerius** [comment]
Seeing how OP hasn't responded anymore, please go ahead and close this issue report.
